[run]
  deadline = "10m"
  tests = true

[linters]
  disable-all = true
  enable = [
    "asciicheck",
    "bidichk",
    "contextcheck",
    "deadcode",
    "depguard",
    "dogsled",
    "dupl",
    "errname",
    "exportloopref",
    "forcetypeassert",
    "funlen",
    "gocognit",
    "goconst",
    "gocritic",
    "gocyclo",
    "godot",
    "gofumpt",
    "gosimple",
    "govet",
    "ifshort",
    "ineffassign",
    "misspell",
    "nakedret",
    "nestif",
    "nilerr",
    "nilnil",
    "nolintlint",
    "prealloc",
    "predeclared",
    "staticcheck",
    "structcheck",
    "stylecheck",
    "typecheck",
    "unconvert",
    "unparam",
    "unused",
    "varcheck",
    "vetshadow",
    "wastedassign",
    "whitespace",
  ]

[issues]
  fix = true

[linters-settings.gofumpt]
    extra-rules = true

[linters-settings.stylecheck]
    checks = ["all", "-ST1003"]
